# Generated by Django 4.2.8 on 2023-12-22 16:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0002_initial"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("services", "0001_initial"),
        ("taxonomy", "0001_initial"),
        ("work", "0001_initial"),
        ("people", "0001_initial"),
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subservicepagefeaturedcasestudy",
            name="case_study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="work.workpage"
            ),
        ),
        migrations.AddField(
            model_name="subservicepagefeaturedcasestudy",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_case_studies",
                to="services.subservicepage",
            ),
        ),
        migrations.AddField(
            model_name="subservicepagefeaturedblogpost",
            name="blog_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogpage"
            ),
        ),
        migrations.AddField(
            model_name="subservicepagefeaturedblogpost",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_blog_posts",
                to="services.subservicepage",
            ),
        ),
        migrations.AddField(
            model_name="subservicepageclientlogo",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.customimage"
            ),
        ),
        migrations.AddField(
            model_name="subservicepageclientlogo",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_logos",
                to="services.subservicepage",
            ),
        ),
        migrations.AddField(
            model_name="subservicepage",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="people.contact",
            ),
        ),
        migrations.AddField(
            model_name="subservicepage",
            name="contact_reasons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="people.contactreasonslist",
            ),
        ),
        migrations.AddField(
            model_name="subservicepage",
            name="social_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="servicepageusaclientlogo",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.customimage"
            ),
        ),
        migrations.AddField(
            model_name="servicepageusaclientlogo",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usa_client_logos",
                to="services.servicepage",
            ),
        ),
        migrations.AddField(
            model_name="servicepagetestimonial",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testimonials",
                to="services.servicepage",
            ),
        ),
        migrations.AddField(
            model_name="servicepageprocess",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processes",
                to="services.servicepage",
            ),
        ),
        migrations.AddField(
            model_name="servicepageprocess",
            name="page_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="servicepagekeypoint",
            name="linked_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="servicepagekeypoint",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="key_points",
                to="services.servicepage",
            ),
        ),
        migrations.AddField(
            model_name="servicepagefeaturedcasestudy",
            name="case_study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="work.workpage"
            ),
        ),
        migrations.AddField(
            model_name="servicepagefeaturedcasestudy",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_case_studies",
                to="services.servicepage",
            ),
        ),
        migrations.AddField(
            model_name="servicepagefeaturedblogpost",
            name="blog_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogpage"
            ),
        ),
        migrations.AddField(
            model_name="servicepagefeaturedblogpost",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_blog_posts",
                to="services.servicepage",
            ),
        ),
        migrations.AddField(
            model_name="servicepageclientlogo",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.customimage"
            ),
        ),
        migrations.AddField(
            model_name="servicepageclientlogo",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_logos",
                to="services.servicepage",
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="people.contact",
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="contact_reasons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="people.contactreasonslist",
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="service",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to this service in taxonomy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="taxonomy.service",
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="social_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
