# Generated by Django 4.2.9 on 2024-02-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_move_blog_and_work_chooser_to_streamfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("theme-coral", "Coral"),
                    ("theme-lagoon", "Lagoon"),
                    ("theme-banana", "Banana"),
                ],
                help_text="The theme will be applied to this page and all of its descendants. If no theme is selected, it will be derived from this page's ancestors.",
                max_length=25,
            ),
        ),
    ]
