# Generated by Django 4.2.11 on 2024-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0020_merge_20240315_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="navigation_text",
            field=models.CharField(
                blank=True,
                help_text="\n            Text entered here will appear instead of the page title in the navigation menu.\n            For top-level menu items do this in the navigaiton settings instead.\n            ",
                max_length=255,
            ),
        ),
    ]
