# Generated by Django 4.2.9 on 2024-01-15 11:15

from django.db import migrations

from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import RenameStreamChildrenOperation


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0076_modellogentry_revision"),
        ("blog", "0003_add_new_image_block_to_body_streamfield"),
    ]

    operations = [
        MigrateStreamData(
            app_name="blog",
            model_name="BlogPage",
            field_name="body",
            operations_and_block_paths=[
                (
                    RenameStreamChildrenOperation(
                        old_name="wide_image", new_name="image"
                    ),
                    "",
                ),
                (
                    RenameStreamChildrenOperation(
                        old_name="aligned_image", new_name="image"
                    ),
                    "",
                ),
            ],
        ),
    ]
