# Generated by Django 4.2.9 on 2024-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpage_body"),
        ("blog", "0005_remove_aligned_and_wide_image_blocks_from_body_streamfield"),
    ]

    operations = []
