# Generated by Django 4.2.9 on 2024-01-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blogpage_body"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPageRelatedLink",
        ),
    ]
