# Generated by Django 4.2.9 on 2024-01-25 08:44

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_remove_blogpagetagselect_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpageauthor",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_authors",
                to="blog.blogpage",
            ),
        ),
    ]
