# Generated by Django 4.2.9 on 2024-01-25 08:44

from django.db import migrations


def use_core_page_author(apps, schema_editor):
    """
    We are retiring blog.BlogPageAuthor in favour of torchbox.PageAuthor
    """

    Blog = apps.get_model("blog", "BlogPage")
    PageAuthor = apps.get_model("torchbox", "PageAuthor")

    blogs = Blog.objects.all()
    for blog in blogs:
        authors = blog.page_authors.all()
        for person in authors:
            PageAuthor.objects.create(author=person.author, page=blog)


def use_blog_page_author(apps, schema_editor):
    """
    Revert to blog.BlogPageAuthor from torchbox.PageAuthor
    """

    Blog = apps.get_model("blog", "BlogPage")
    BlogPageAuthor = apps.get_model("blog", "BlogPageAuthor")

    blogs = Blog.objects.all()
    for blog in blogs:
        authors = blog.authors.all()
        for person in authors:
            BlogPageAuthor.objects.create(author=person.author, page=blog)


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_blogpageauthor_page"),
        ("torchbox", "0014_data_migration_pageauthor"),
    ]

    operations = [
        migrations.RunPython(use_core_page_author, use_blog_page_author),
    ]
