# Generated by Django 4.2.9 on 2024-01-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_data_migration_page_authors"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPageAuthor",
        ),
    ]
