# Generated by Django 4.2.9 on 2024-01-26 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_blogpage_body"),
        ("blog", "0014_delete_blogpageauthor"),
    ]

    operations = []
