# Generated by Django 4.2.9 on 2024-03-11 19:43

from django.db import migrations
import tbx.core.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_add_wide_image_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=tbx.core.utils.fields.StreamField(use_json_field=True),
        ),
    ]
