# Generated by Django 5.1.4 on 2025-01-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0027_update_theme_colour_choices"),
        ("divisions", "0002_divisionmixin_and_navigationsetmixin"),
        ("navigation", "0007_divisionmixin_and_navigationsetmixin"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="divisions.divisionpage",
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="override_navigation_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="navigation.navigationset",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="divisions.divisionpage",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="override_navigation_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="navigation.navigationset",
            ),
        ),
    ]
