# Generated by Django 5.1.5 on 2025-04-10 13:39

from django.db import migrations, models
import django.db.models.deletion

import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0028_divisionmixin_and_navigationsetmixin"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedBlogPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="blog.blogpage",
                    ),
                ),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_posts",
                        to="blog.blogpage",
                    ),
                ),
            ],
        ),
    ]
