# Generated by Django 5.2.5 on 2025-10-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0029_relatedblogpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="introduction",
            field=models.TextField(blank=True),
        ),
    ]
