# Generated by Django 5.2.5 on 2025-10-22 09:34

from django.db import migrations

import tbx.core.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0030_adds_introduction_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="page_links",
            field=tbx.core.utils.fields.StreamField(
                blank=True, block_lookup={}, help_text="Add up to 3 styled page links."
            ),
        ),
    ]
