# Generated by Django 5.2.15 on 2026-06-30 15:55

from django.db import migrations, models
import django.db.models.deletion

import tbx.core.utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("divisions", "0004_remove_override_navigation_set"),
        ("images", "0002_customimage_description"),
        ("people", "0013_remove_override_navigation_set"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "navigation_text",
                    models.CharField(
                        blank=True,
                        help_text="\n            Text entered here will appear instead of the page title in the navigation menu.\n            For top-level menu items do this in the navigaiton settings instead.\n            ",
                        max_length=255,
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("theme-coral", "Coral"),
                            ("theme-nebuline", "Nebuline"),
                            ("theme-lagoon", "Lagoon"),
                            ("theme-green", "Green"),
                        ],
                        max_length=25,
                    ),
                ),
                ("hero", tbx.core.utils.fields.StreamField(block_lookup={})),
                (
                    "body",
                    tbx.core.utils.fields.StreamField(blank=True, block_lookup={}),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="The contact will be applied to this page's footer and all of its descendants.\nIf no contact is selected, it will be derived from this page's ancestors, eventually falling back to the default contact.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="people.contact",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="divisions.divisionpage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
