# Generated by Django 4.2.9 on 2024-02-09 11:55

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_sector_team_remove_service_contact_reasons_and_more"),
        ("people", "0004_personindexpage_theme_personpage_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personpage",
            name="is_senior",
        ),
        migrations.AddField(
            model_name="personpage",
            name="related_teams",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="people", to="taxonomy.team"
            ),
        ),
    ]
