# Generated by Django 4.2.9 on 2024-01-17 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0004_alter_workpage_body"),
        ("work", "0005_remove_aligned_and_wide_image_blocks_from_body_streamfield"),
    ]

    operations = []
