# Generated by Django 4.2.9 on 2024-01-22 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0001_initial"),
        ("images", "0001_initial"),
        ("people", "0003_remove_personindexpage_call_to_action_and_more"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("work", "0010_add_help_text_to_alt_text_field_in_image_block"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkPage",
            new_name="HistoricalWorkPage",
        ),
        migrations.RenameModel(
            old_name="WorkPageAuthor",
            new_name="HistoricalWorkPageAuthor",
        ),
        migrations.RenameModel(
            old_name="WorkPageScreenshot",
            new_name="HistoricalWorkPageScreenshot",
        ),
        migrations.RemoveField(
            model_name="workindexpage",
            name="hide_popular_tags",
        ),
        migrations.DeleteModel(
            name="WorkPageTagSelect",
        ),
    ]
