# Generated by Django 4.2.9 on 2024-01-25 08:49

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("taxonomy", "0001_initial"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("work", "0010_add_help_text_to_alt_text_field_in_image_block"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkPage",
            new_name="HistoricalWorkPage",
        ),
        migrations.RenameModel(
            old_name="WorkPageScreenshot",
            new_name="HistoricalWorkPageScreenshot",
        ),
        migrations.RemoveField(
            model_name="workindexpage",
            name="hide_popular_tags",
        ),
        migrations.AlterField(
            model_name="workpageauthor",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_authors",
                to="work.historicalworkpage",
            ),
        ),
        migrations.DeleteModel(
            name="WorkPageTagSelect",
        ),
    ]
