# Generated by Django 4.2.9 on 2024-01-25 08:50

from django.db import migrations


def use_core_page_author(apps, schema_editor):
    """
    We are retiring work.WorkPageAuthor in favour of torchbox.PageAuthor
    """

    Work = apps.get_model("work", "HistoricalWorkPage")
    PageAuthor = apps.get_model("torchbox", "PageAuthor")

    works = Work.objects.all()
    for work in works:
        authors = work.page_authors.all()
        for person in authors:
            PageAuthor.objects.create(author=person.author, page=work)


def use_work_page_author(apps, schema_editor):
    """
    Revert to work.WorkPageAuthor from torchbox.PageAuthor
    """

    Work = apps.get_model("work", "HistoricalWorkPage")
    WorkPageAuthor = apps.get_model("work", "WorkPageAuthor")

    works = Work.objects.all()
    for work in works:
        authors = work.authors.all()
        for person in authors:
            WorkPageAuthor.objects.create(author=person.author, page=work)


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0011_rename_workpage_historicalworkpage_and_more"),
        ("torchbox", "0014_data_migration_pageauthor"),
    ]

    operations = [
        migrations.RunPython(use_core_page_author, use_work_page_author),
    ]
