# Generated by Django 4.2.9 on 2024-01-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0011_alter_workpage_body"),
        ("work", "0014_add_new_workpage_model"),
    ]

    operations = []
