# Generated by Django 4.2.9 on 2024-01-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0016_alter_historicalworkpage_body_alter_workpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workindexpage",
            name="intro",
        ),
    ]
