# Generated by Django 4.2.9 on 2024-01-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("work", "0017_alter_historicalworkpage_body_alter_workpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workpage",
            name="header_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="Image",
            ),
        ),
    ]
