# Generated by Django 4.2.9 on 2024-01-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0017_alter_historicalworkpage_body_alter_workpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workindexpage",
            name="intro",
        ),
    ]
