# Generated by Django 4.2.9 on 2024-01-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("work", "0018_make_work_page_image_compulsory"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpage",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
