# Generated by Django 4.2.9 on 2024-01-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0019_add_logo_to_work_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workpage",
            name="client",
            field=models.CharField(max_length=255),
        ),
    ]
