# Generated by Django 4.2.9 on 2024-01-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0019_work_page_changes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workindexpage",
            name="intro",
        ),
    ]
