# Generated by Django 4.2.9 on 2024-02-06 10:56

from django.db import migrations

import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0002_sector_team_remove_service_contact_reasons_and_more"),
        ("work", "0021_historicalworkpage_theme_workindexpage_theme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkpage",
            name="related_sectors",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="historical_case_studies", to="taxonomy.sector"
            ),
        ),
        migrations.AddField(
            model_name="workpage",
            name="related_sectors",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="case_studies", to="taxonomy.sector"
            ),
        ),
    ]
