# Generated by Django 4.2.9 on 2024-03-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0028_remove_homepage_image_and_screenshot_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalworkpage",
            old_name="feed_image",
            new_name="header_image",
        ),
    ]
