# Generated by Django 4.2.9 on 2024-03-11 19:43

from django.db import migrations

import tbx.core.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0028_remove_homepage_image_and_screenshot_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalworkpage",
            name="body",
            field=tbx.core.utils.fields.StreamField(use_json_field=True),
        ),
        migrations.AlterField(
            model_name="workpage",
            name="body",
            field=tbx.core.utils.fields.StreamField(use_json_field=True),
        ),
    ]
