# Generated by Django 4.2.9 on 2024-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0029_use_custom_streamfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpage",
            name="desaturate_header_image",
            field=models.BooleanField(default=True),
        ),
    ]
