# Manually combined migrations which were generated by Django 4.2.9 on 2024-03-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("work", "0029_use_custom_streamfield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalworkpage",
            old_name="feed_image",
            new_name="header_image",
        ),
        migrations.AlterField(
            model_name="historicalworkpage",
            name="header_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image used on listings and social media.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="Feed image",
            ),
        ),
        
    ]
