# Generated by Django 4.2.13 on 2024-07-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0034_add_earth_colour_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpage",
            name="header_alt_text",
            field=models.CharField(
                blank=True,
                help_text="By default the image title (shown above) is used as the alt text. Use this field to provide more specific alt text if required.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="workpage",
            name="header_image_is_decorative",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this will make the alt text empty.",
            ),
        ),
    ]
