# Generated by Django 4.2.16 on 2024-12-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0035_add_alt_text_options_to_work_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalworkpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("theme-coral", "Coral"),
                    ("theme-nebuline", "Nebuline"),
                    ("theme-lagoon", "Lagoon"),
                    ("theme-green", "Green"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="workindexpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("theme-coral", "Coral"),
                    ("theme-nebuline", "Nebuline"),
                    ("theme-lagoon", "Lagoon"),
                    ("theme-green", "Green"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="workpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("theme-coral", "Coral"),
                    ("theme-nebuline", "Nebuline"),
                    ("theme-lagoon", "Lagoon"),
                    ("theme-green", "Green"),
                ],
                max_length=25,
            ),
        ),
    ]
