# Generated by Django 4.2.8 on 2024-01-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobindexpagejob",
            name="page",
        ),
        migrations.DeleteModel(
            name="JobIndexPage",
        ),
        migrations.DeleteModel(
            name="JobIndexPageJob",
        ),
    ]
