# Generated by Django 4.2.9 on 2024-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0007_alter_standardpage_body"),
        ("torchbox", "0008_remove_aligned_and_wide_image_blocks_from_body_streamfield"),
    ]

    operations = []
