# Generated by Django 4.2.9 on 2024-01-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0014_servicepagefeaturedworkpost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardpage",
            name="featured_blog_heading",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="featured_work_post_heading",
            field=models.TextField(blank=True),
        ),
    ]
