# Generated by Django 4.2.9 on 2024-01-26 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("torchbox", "0014_alter_standardpage_body"),
        ("torchbox", "0014_data_migration_pageauthor"),
    ]

    operations = []
