# Generated by Django 4.2.9 on 2024-02-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0024_add_wide_image_block"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="statement",
        ),
    ]
