# Generated by Django 4.2.9 on 2024-02-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0025_add_tabbed_paragraph_block"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="statement",
        ),
    ]
