# Generated by Django 4.2.9 on 2024-03-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0026_add_event_block_to_homepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="statement",
        ),
    ]
