# Generated by Django 4.2.9 on 2024-03-11 12:55

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("torchbox", "0029_update_button_link_on_photocollageblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "showcase",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    "showcase_paragraphs",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("heading", wagtail.blocks.CharBlock()),
                                                (
                                                    "summary",
                                                    wagtail.blocks.RichTextBlock(),
                                                ),
                                                (
                                                    "page",
                                                    wagtail.blocks.PageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ],
                                            help_text="Add a showcase paragraph, with summary text and an optional page link",
                                            icon="breadcrumb-expand",
                                        ),
                                        help_text="Add at least two showcase paragraphs",
                                        max_num=10,
                                        min_num=2,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "featured_case_study",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "link",
                                    wagtail.blocks.PageChooserBlock(
                                        page_type=[
                                            "work.WorkPage",
                                            "work.HistoricalWorkPage",
                                        ]
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "logo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "blog_chooser",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "featured_blog_heading",
                                    wagtail.blocks.CharBlock(max_length=255),
                                ),
                                (
                                    "blog_pages",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.PageChooserBlock(
                                            page_type=["blog.BlogPage"]
                                        ),
                                        max_num=3,
                                        min_num=1,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "work_chooser",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "featured_work_heading",
                                    wagtail.blocks.CharBlock(max_length=255),
                                ),
                                (
                                    "work_pages",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.PageChooserBlock(
                                            page_type=[
                                                "work.WorkPage",
                                                "work.HistoricalWorkPage",
                                            ]
                                        ),
                                        max_num=3,
                                        min_num=1,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "photo_collage",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    "intro",
                                    wagtail.blocks.TextBlock(label="Introduction"),
                                ),
                                (
                                    "button_link",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.blocks.PageChooserBlock(),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.blocks.URLBlock(),
                                            ),
                                        ],
                                        max_num=1,
                                        required=False,
                                    ),
                                ),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=55, required=False
                                    ),
                                ),
                                (
                                    "images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(),
                                                ),
                                                (
                                                    "alt_text",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="By default the image title (shown above) is used as the alt text. Use this field to provide more specific alt text if required.",
                                                        required=False,
                                                    ),
                                                ),
                                            ],
                                            label="Photo",
                                        ),
                                        default=[
                                            {"alt_text": "", "image": None},
                                            {"alt_text": "", "image": None},
                                            {"alt_text": "", "image": None},
                                            {"alt_text": "", "image": None},
                                            {"alt_text": "", "image": None},
                                            {"alt_text": "", "image": None},
                                        ],
                                        help_text="Exactly six required.",
                                        label="Photos",
                                        max_num=6,
                                        min_num=6,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "promo",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.TextBlock()),
                                ("description", wagtail.blocks.TextBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(max_length=55),
                                ),
                                (
                                    "button_link",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.blocks.PageChooserBlock(),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.blocks.URLBlock(),
                                            ),
                                            ("email", wagtail.blocks.EmailBlock()),
                                        ],
                                        max_num=1,
                                        required=True,
                                    ),
                                ),
                                (
                                    "secondary_link",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(),
                                                        ),
                                                        (
                                                            "link_text",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "link_url",
                                                            wagtail.blocks.URLBlock(
                                                                label="URL"
                                                            ),
                                                        ),
                                                        (
                                                            "link_text",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        label="Secondary link",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "tabbed_paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    "intro",
                                    wagtail.blocks.TextBlock(label="Introduction"),
                                ),
                                (
                                    "tabbed_paragraph_sections",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("name", wagtail.blocks.CharBlock()),
                                                ("summary", wagtail.blocks.TextBlock()),
                                                (
                                                    "text",
                                                    wagtail.blocks.RichTextBlock(),
                                                ),
                                                (
                                                    "button_text",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "button_link",
                                                    wagtail.blocks.PageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ],
                                            help_text="Add a tabbed paragraph, with a name, summary, text and an optional page link & button text",
                                            icon="breadcrumb-expand",
                                        ),
                                        help_text="Add at least two tabbed paragraph sections",
                                        min_num=2,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "event",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    "url",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.blocks.PageChooserBlock(),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.blocks.URLBlock(),
                                            ),
                                            ("email", wagtail.blocks.EmailBlock()),
                                        ],
                                        max_num=1,
                                        required=True,
                                    ),
                                ),
                                (
                                    "type",
                                    wagtail.blocks.ListBlock(
                                        wagtail.snippets.blocks.SnippetChooserBlock(
                                            "torchbox.EventType"
                                        ),
                                        min_num=1,
                                    ),
                                ),
                                ("start_date", wagtail.blocks.DateBlock()),
                                (
                                    "start_time",
                                    wagtail.blocks.TimeBlock(required=False),
                                ),
                                ("end_date", wagtail.blocks.DateBlock(required=False)),
                                ("end_time", wagtail.blocks.TimeBlock(required=False)),
                                ("location", wagtail.blocks.TextBlock(required=False)),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "secondary_link",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(),
                                                        ),
                                                        (
                                                            "link_text",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "link_url",
                                                            wagtail.blocks.URLBlock(
                                                                label="URL"
                                                            ),
                                                        ),
                                                        (
                                                            "link_text",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        label="Secondary link",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
