# Generated by Django 4.2.9 on 2024-03-11 19:43

from django.db import migrations

import tbx.core.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("torchbox", "0029_update_button_link_on_photocollageblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="addresses",
            field=tbx.core.utils.fields.StreamField(blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=tbx.core.utils.fields.StreamField(use_json_field=True),
        ),
        migrations.AlterField(
            model_name="mainmenu",
            name="menu",
            field=tbx.core.utils.fields.StreamField(blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=tbx.core.utils.fields.StreamField(use_json_field=True),
        ),
    ]
