# Generated by Django 4.2.9 on 2024-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0031_merge_20240315_1052"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediasettings",
            name="site_name",
            field=models.CharField(
                blank=True,
                default="Torchbox",
                help_text="Site name, used by Open Graph.",
                max_length=255,
            ),
        ),
    ]
