# Generated by Django 4.2.11 on 2024-07-24 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("torchbox", "0034_add_earth_colour_theme"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GlobalSettings",
        ),
    ]
