# Generated by Django 4.2.11 on 2024-07-24 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("torchbox", "0035_remove_address_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
    ]
