# Generated by Django 4.2.11 on 2024-07-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0035_remove_address_settings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
