# Generated by Django 4.2.11 on 2024-07-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0035_add_important_page_settings"),
        ("torchbox", "0036_delete_unused_tag_snippet"),
    ]

    operations = []
