# Generated by Django 4.2.16 on 2024-12-04 08:04

from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("torchbox", "0038_update_theme_colour_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="introduction",
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_heading_1",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_heading_2",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_introduction",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
