# Generated by Django 5.2.15 on 2026-06-22 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("torchbox", "0044_eventtype_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventtype",
            options={"ordering": ["name"]},
        ),
    ]
