# Generated by Django 4.2.8 on 2024-01-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.IntegerField()),
                (
                    "contact_reasons",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="people.contactreasonslist",
                    ),
                ),
                (
                    "preferred_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="people.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
