# Generated by Django 4.2.8 on 2023-12-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
        ("propositions", "0001_initial"),
        ("images", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subservicepagetosubpropositionpagemigration",
            name="subservice_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="services.subservicepage",
            ),
        ),
        migrations.AddField(
            model_name="subpropositionpage",
            name="social_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="propositionpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="propositionpage",
            name="service",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to this service in taxonomy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="taxonomy.service",
            ),
        ),
        migrations.AddField(
            model_name="propositionpage",
            name="social_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
