# Generated by Django 4.2.9 on 2024-02-07 22:21

from django.db import migrations

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "external_link",
                                    wagtail.blocks.URLBlock(required=False),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "hide_children",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="By default, the navigation menu displays the children and grandchildren of the selected page if their <strong>Show in menus</strong> checkbox is checked.<br />If you tick this checkbox, the navigation will exclude them, regardless of their <strong>Show in menus</strong> settings.",
                                        label="Do not show child pages",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Main site navigation",
                use_json_field=True,
            ),
        ),
    ]
