# Generated by Django 4.2.9 on 2024-02-08 17:24

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0002_alter_navigationsettings_primary_navigation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_logos",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock())],
                blank=True,
                help_text="Single list of logos that appear before the footer box",
                use_json_field=True,
            ),
        ),
    ]
