# Generated by Django 4.2.9 on 2024-02-16 17:56

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0003_alter_navigationsettings_footer_logos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_logos",
            field=wagtail.fields.StreamField(
                [
                    (
                        "logo",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.blocks.URLBlock(required=False),
                                            ),
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Leave blank to use the page's own title",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Single list of logos that appear before the footer box",
                use_json_field=True,
            ),
        ),
    ]
