# Generated by Django 4.2.9 on 2024-03-07 11:27

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0004_alter_navigationsettings_footer_logos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "external_link",
                                    wagtail.blocks.URLBlock(required=False),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "child_display_behaviour",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            (
                                                "hide_children",
                                                "Do not show child pages",
                                            ),
                                            (
                                                "show_up_to_level1",
                                                "Show child pages up to level 1 (children)",
                                            ),
                                            (
                                                "show_up_to_level2",
                                                "Show child pages up to level 2 (grandchildren)",
                                            ),
                                        ],
                                        help_text="By default, the navigation menu displays the children and grandchildren of the selected page if their “Show in menus” checkbox  is checked.<br/>You can alter this behaviour here.",
                                        icon="collapse-down",
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Main site navigation",
                use_json_field=True,
            ),
        ),
    ]
