# Generated by Django 5.1.5 on 2025-02-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0007_divisionmixin_and_navigationsetmixin"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationsettings",
            name="footer_newsletter_cta_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="navigationsettings",
            name="footer_newsletter_cta_url",
            field=models.URLField(blank=True),
        ),
    ]
