# Generated by Django 5.2.12 on 2026-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0008_navigationsettings_footer_newsletter_cta"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationsettings",
            name="carbon_impact_figure",
            field=models.FloatField(
                blank=True,
                help_text="Estimated carbon emitted (in grams) when loading the home page. Updates here should be reflected in our Digital emissions page.",
                null=True,
            ),
        ),
    ]
