# Generated by Django 5.2.15 on 2026-07-22 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0009_navigationsettings_carbon_impact_figure"),
        ("navigation", "0012_alter_navigationsettings_primary_navigation"),
    ]

    operations = []
