# Generated by Django 5.1.4 on 2025-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("divisions", "0002_divisionmixin_and_navigationsetmixin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="divisionpage",
            name="label",
        ),
        migrations.AddField(
            model_name="divisionpage",
            name="logo",
            field=models.CharField(
                choices=[
                    ("logo-torchbox", "Torchbox"),
                    ("logo-charity", "Torchbox Charity"),
                    ("logo-public", "Torchbox Public"),
                    ("logo-wagtail", "Torchbox Wagtail"),
                ],
                default="logo-torchbox",
                max_length=50,
            ),
        ),
    ]
