# Generated by Django 5.2.15 on 2026-07-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("divisions", "0005_divisionpage_sector"),
        ("taxonomy", "0002_sector_team_remove_service_contact_reasons_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="divisionpage",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="division_pages",
                to="taxonomy.service",
            ),
        ),
    ]
