# Generated by Django 5.2.2 on 2026-04-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("divisions", "0003_remove_divisionpage_label_divisionpage_logo"),
        ("images", "0002_customimage_description"),
        ("navigation", "0008_navigationsettings_footer_newsletter_cta"),
        ("people", "0012_divisionmixin_and_navigationsetmixin"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitemapPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "navigation_text",
                    models.CharField(
                        blank=True,
                        help_text="\n            Text entered here will appear instead of the page title in the navigation menu.\n            For top-level menu items do this in the navigaiton settings instead.\n            ",
                        max_length=255,
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("theme-coral", "Coral"),
                            ("theme-nebuline", "Nebuline"),
                            ("theme-lagoon", "Lagoon"),
                            ("theme-green", "Green"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="The contact will be applied to this page's footer and all of its descendants.\nIf no contact is selected, it will be derived from this page's ancestors, eventually falling back to the default contact.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="people.contact",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="divisions.divisionpage",
                    ),
                ),
                (
                    "override_navigation_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="navigation.navigationset",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitemap page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
