# Generated by Django 4.2.9 on 2024-03-28 11:28

from django.db import migrations, models
import django.db.models.deletion
import tbx.core.utils.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactReportPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("strapline", models.CharField(max_length=255)),
                (
                    "introduction_title",
                    models.CharField(default="Introduction", max_length=255),
                ),
                ("introduction", wagtail.fields.RichTextField(blank=True)),
                ("body", tbx.core.utils.fields.StreamField(use_json_field=True)),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is for the illustration only. Use an image with dimensions of 571x700",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
