# Generated by Django 4.2.9 on 2024-03-27 11:14

from django.db import migrations, models
import django.db.models.deletion
import tbx.core.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
import wagtailmarkdown.blocks
import wagtailmedia.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactReportPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("strapline", models.CharField(max_length=255)),
                (
                    "introduction_title",
                    models.CharField(default="Introduction", max_length=255),
                ),
                ("introduction", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "h2",
                                wagtail.blocks.CharBlock(
                                    form_classname="title",
                                    group="Basics",
                                    icon="title",
                                    template="patterns/molecules/streamfield/blocks/heading2_block.html",
                                ),
                            ),
                            (
                                "h3",
                                wagtail.blocks.CharBlock(
                                    form_classname="title",
                                    group="Basics",
                                    icon="title",
                                    template="patterns/molecules/streamfield/blocks/heading3_block.html",
                                ),
                            ),
                            (
                                "h4",
                                wagtail.blocks.CharBlock(
                                    form_classname="title",
                                    group="Basics",
                                    icon="title",
                                    template="patterns/molecules/streamfield/blocks/heading4_block.html",
                                ),
                            ),
                            (
                                "intro",
                                wagtail.blocks.RichTextBlock(
                                    group="Basics",
                                    icon="pilcrow",
                                    template="patterns/molecules/streamfield/blocks/intro_block.html",
                                ),
                            ),
                            (
                                "paragraph",
                                wagtail.blocks.RichTextBlock(
                                    group="Basics",
                                    icon="pilcrow",
                                    template="patterns/molecules/streamfield/blocks/paragraph_block.html",
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="By default the image title (shown above) is used as the alt text. Use this field to provide more specific alt text if required.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "remove_desaturation_filter",
                                            wagtail.blocks.BooleanBlock(
                                                default=False,
                                                help_text="Do not apply a desaturation filter to the image.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image_is_decorative",
                                            wagtail.blocks.BooleanBlock(
                                                default=False,
                                                help_text="If checked, this will make the alt text empty.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "attribution",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                    ],
                                    group="Media and images",
                                    template="patterns/molecules/streamfield/blocks/image_block.html",
                                ),
                            ),
                            (
                                "wide_image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="By default the image title (shown above) is used as the alt text. Use this field to provide more specific alt text if required.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "remove_desaturation_filter",
                                            wagtail.blocks.BooleanBlock(
                                                default=False,
                                                help_text="Do not apply a desaturation filter to the image.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image_is_decorative",
                                            wagtail.blocks.BooleanBlock(
                                                default=False,
                                                help_text="If checked, this will make the alt text empty.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "attribution",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                    ],
                                    group="Media and images",
                                    template="patterns/molecules/streamfield/blocks/wide_image_block.html",
                                ),
                            ),
                            (
                                "call_to_action",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                max_length=255, required=True
                                            ),
                                        ),
                                        (
                                            "button_text",
                                            wagtail.blocks.CharBlock(max_length=55),
                                        ),
                                        (
                                            "button_link",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.blocks.PageChooserBlock(),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.blocks.URLBlock(),
                                                    ),
                                                    (
                                                        "email",
                                                        wagtail.blocks.EmailBlock(),
                                                    ),
                                                ],
                                                max_num=1,
                                                required=True,
                                            ),
                                        ),
                                    ],
                                    group="Calls to action",
                                    label="Call to Action",
                                    template="patterns/molecules/streamfield/blocks/call_to_action.html",
                                ),
                            ),
                            (
                                "contact_call_to_action",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "call_to_action",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "call_to_action",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "text",
                                                                    wagtail.blocks.CharBlock(
                                                                        max_length=255,
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "button_text",
                                                                    wagtail.blocks.CharBlock(
                                                                        max_length=55
                                                                    ),
                                                                ),
                                                                (
                                                                    "button_link",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "internal_link",
                                                                                wagtail.blocks.PageChooserBlock(),
                                                                            ),
                                                                            (
                                                                                "external_link",
                                                                                wagtail.blocks.URLBlock(),
                                                                            ),
                                                                            (
                                                                                "email",
                                                                                wagtail.blocks.EmailBlock(),
                                                                            ),
                                                                        ],
                                                                        max_num=1,
                                                                        required=True,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    )
                                                ],
                                                max_num=1,
                                            ),
                                        ),
                                        (
                                            "person",
                                            wagtail.snippets.blocks.SnippetChooserBlock(
                                                "people.Author"
                                            ),
                                        ),
                                    ],
                                    group="Calls to action",
                                    label="Contact Call to Action",
                                    template="patterns/molecules/streamfield/blocks/contact_call_to_action.html",
                                ),
                            ),
                            (
                                "pullquote",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "quote",
                                            wagtail.blocks.CharBlock(
                                                form_classname="quote title"
                                            ),
                                        ),
                                        ("attribution", wagtail.blocks.CharBlock()),
                                        (
                                            "role",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "logo",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="You may optionally add either a company logo or author image",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "author_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="You may optionally add either a company logo or author image",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "call_to_action",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "page",
                                                                    wagtail.blocks.PageChooserBlock(),
                                                                ),
                                                                (
                                                                    "link_text",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "link_url",
                                                                    wagtail.blocks.URLBlock(
                                                                        label="URL"
                                                                    ),
                                                                ),
                                                                (
                                                                    "link_text",
                                                                    wagtail.blocks.CharBlock(),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    group="Basics",
                                    template="patterns/molecules/streamfield/blocks/pullquote_block.html",
                                ),
                            ),
                            (
                                "raw_html",
                                wagtail.blocks.RawHTMLBlock(
                                    group="Special",
                                    icon="code",
                                    label="Raw HTML",
                                    template="patterns/molecules/streamfield/blocks/raw_html_block.html",
                                ),
                            ),
                            (
                                "mailchimp_form",
                                wagtail.blocks.RawHTMLBlock(
                                    group="Special",
                                    icon="code",
                                    label="Mailchimp embedded form",
                                    template="patterns/molecules/streamfield/blocks/mailchimp_form_block.html",
                                ),
                            ),
                            (
                                "markdown",
                                wagtailmarkdown.blocks.MarkdownBlock(
                                    group="Special",
                                    help_text="\n            Use this block to add code snippets.\n            Don't use it for headings or other markdown content,\n            as they will not be styled correctly.\n            To use syntax highlighting, specify the language after the triple backticks, e.g.:\n            ```python\n            ",
                                    icon="code",
                                    label="Code block",
                                    template="patterns/molecules/streamfield/blocks/markdown_block.html",
                                ),
                            ),
                            (
                                "embed",
                                tbx.core.blocks.EmbedBlock(group="Media and images"),
                            ),
                            (
                                "video_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "video",
                                            wagtailmedia.blocks.VideoChooserBlock(),
                                        ),
                                        (
                                            "autoplay",
                                            wagtail.blocks.BooleanBlock(
                                                default=False,
                                                help_text="Automatically start and loop the video. Please use sparingly.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "use_original_width",
                                            wagtail.blocks.BooleanBlock(
                                                default=False,
                                                help_text="Use the original width of the video instead of the default content width. Note that videos wider than the content width will be limited to the content width.",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "impact_report_heading",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "short_heading",
                                            wagtail.blocks.CharBlock(
                                                help_text="Used for the Table of Contents",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                    ],
                                    group="Impact Report",
                                ),
                            ),
                            (
                                "paragraph_with_quote",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("text", wagtail.blocks.RichTextBlock()),
                                        (
                                            "quote",
                                            wagtail.blocks.RichTextBlock(
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "link",
                                                    "document-link",
                                                ]
                                            ),
                                        ),
                                        (
                                            "attribution",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "quote_alignment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                ]
                                            ),
                                        ),
                                    ],
                                    group="Impact Report",
                                ),
                            ),
                            (
                                "paragraph_with_image",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("text", wagtail.blocks.RichTextBlock()),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "image_alignment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                ]
                                            ),
                                        ),
                                    ],
                                    group="Impact Report",
                                ),
                            ),
                            (
                                "three_column_image_grid",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "items",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                    ]
                                                ),
                                                max_num=3,
                                                min_num=3,
                                            ),
                                        )
                                    ],
                                    group="Impact Report",
                                ),
                            ),
                            (
                                "two_column_text_grid",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "items",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                        ),
                                                        (
                                                            "heading",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        )
                                    ],
                                    group="Impact Report",
                                ),
                            ),
                            (
                                "small_image_with_text",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        ("title", wagtail.blocks.CharBlock()),
                                        ("text", wagtail.blocks.RichTextBlock()),
                                    ],
                                    group="Impact Report",
                                ),
                            ),
                            (
                                "instagram_gallery",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "items",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.blocks.URLBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        )
                                    ],
                                    group="Impact Report",
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is for the illustration only. Use an image with dimensions of 571x700",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
