# Generated by Django 4.2.9 on 2024-04-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("impact_reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impactreportpage",
            name="introduction",
        ),
        migrations.RemoveField(
            model_name="impactreportpage",
            name="introduction_title",
        ),
        migrations.RemoveField(
            model_name="impactreportpage",
            name="strapline",
        ),
        migrations.AddField(
            model_name="impactreportpage",
            name="hero_attribution",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="attribution"
            ),
        ),
        migrations.AddField(
            model_name="impactreportpage",
            name="hero_caption",
            field=models.CharField(blank=True, max_length=255, verbose_name="caption"),
        ),
        migrations.AlterField(
            model_name="impactreportpage",
            name="hero_image",
            field=models.ForeignKey(
                help_text="This is for the illustration only. Use an image with dimensions of 571x700",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
