# Generated by Django 4.2.11 on 2024-04-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0007_use_custom_streamfield"),
        ("images", "0001_initial"),
        ("impact_reports", "0002_impact_report_amend_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactreportpage",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="The contact will be applied to this page's footer and all of its descendants.\nIf no contact is selected, it will be derived from this page's ancestors, eventually falling back to the default contact.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="people.contact",
            ),
        ),
        migrations.AddField(
            model_name="impactreportpage",
            name="social_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="impactreportpage",
            name="social_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="impactreportpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("theme-coral", "Coral"),
                    ("theme-lagoon", "Lagoon"),
                    ("theme-banana", "Banana"),
                ],
                help_text="The theme will be applied to this page and all of its descendants. If no theme is selected, it will be derived from this page's ancestors.",
                max_length=25,
            ),
        ),
    ]
