# Generated by Django 4.2.16 on 2024-12-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impact_reports", "0004_add_earth_colour_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impactreportpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("theme-coral", "Coral"),
                    ("theme-nebuline", "Nebuline"),
                    ("theme-lagoon", "Lagoon"),
                    ("theme-green", "Green"),
                ],
                max_length=25,
            ),
        ),
    ]
