# Generated by Django 5.2.5 on 2026-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("impact_reports", "0006_divisionmixin_and_navigationsetmixin"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactreportpage",
            name="hero_alt_text",
            field=models.CharField(
                blank=True,
                help_text="By default the image title (shown above) is used as the alt text. Use this field to provide more specific alt text if required.",
                verbose_name="alt text",
            ),
        ),
        migrations.AddField(
            model_name="impactreportpage",
            name="hero_image_is_decorative",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this will make the alt text empty.",
                verbose_name="is decorative",
            ),
        ),
    ]
