# Generated by Django 4.2.9 on 2024-02-07 14:46

from django.db import migrations, models

import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0002_sector_team_remove_service_contact_reasons_and_more"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventindexpage",
            name="call_to_action",
        ),
        migrations.AddField(
            model_name="event",
            name="related_sectors",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="events", to="taxonomy.sector"
            ),
        ),
        migrations.AddField(
            model_name="eventindexpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("theme-coral", "Coral"),
                    ("theme-lagoon", "Lagoon"),
                    ("theme-banana", "Banana"),
                ],
                help_text="The theme will be applied to this page and all of its descendants. If no theme is selected, it will be derived from this page's ancestors.",
                max_length=25,
            ),
        ),
    ]
