# Generated by Django 4.2.8 on 2023-12-22 16:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
        ("events", "0002_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authors",
                to="people.author",
                verbose_name="Host",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.eventindexpage",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="related_services",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="events", to="taxonomy.service"
            ),
        ),
    ]
