# Generated by Django 4.2.9 on 2024-03-22 14:20

from django.db import migrations
import tbx.core.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_related_sectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventindexpage",
            name="events",
            field=tbx.core.utils.fields.StreamField(blank=True, use_json_field=True),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
