# Generated by Django 4.2.11 on 2024-04-12 08:40

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_eventindexpage_events_delete_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventindexpage",
            name="no_events_message",
            field=wagtail.fields.RichTextField(
                default='<p class="mb-spacerMini">We don\'t have any live events for you to register for at the moment but there will be more coming soon!</p><p class="mb-spacerMini">If you\'d like to be added to the invite list for future events, sign up here.</p> <p>Keep an eye on our social channels for all our news - Twitter, LinkedIn, Instagram</p>',
                help_text="Message to display if there are no events",
            ),
            preserve_default=False,
        ),
    ]
