# Generated by Django 5.2.12 on 2026-04-10 09:27

from django.db import migrations, models

from pgvector.django import VectorExtension
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="CustomPgVectorEmbedding",
            fields=[
                ("index_name", models.CharField(max_length=255)),
                (
                    "document_key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("vector", pgvector.django.vector.VectorField(dimensions=1536)),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["vector"],
                        m=16,
                        name="vector_index",
                        opclasses=["vector_l2_ops"],
                    )
                ],
            },
        ),
    ]
